name: "AniList English"
guid: "fe9c23f6-1eb9-4bfb-b7ca-4557ca2707e3"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-anilist.png"
version: 1
targetAbi: "10.10.6.0"
framework: "net8.0"
owner: "Skael"
overview: "AniList metadata provider"
description: >
  AniList metadata provider

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.AniList.dll"
changelog: |-
  - none
